config/routes.rb
Rails.application.routes.draw do
  resources :folders
  get '/parse', to: 'bookmarks#parse' #for development
  resources :bookmarks
  root to: 'folders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :children, class_name: "Folder", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Folder", required: false
  has_and_belongs_to_many :tags
  belongs_to :category, required: false
  has_many :bookmarks


  def breadcrumb_parents
    # get all parents here into array
    ar = []
    ar << parentf
    ar << parent.breadcrumb_parents
    ar
  end

  def self.root_parents
    Folder.select{|f| f.parent.nil?}.each do |f|
      f.isrootparent = true
      f.save
    end
  end

  def is_rootparent?
    self.isrootparent?
  end

  #
  # def find_all_root_parents
  #   puts "calling this method.. "
  #   Folder.where('parent_id = 1').each do |f|
  #     f.set_rootparent_true
  #   end
  # end

  #TODO refactor names underscore
  #todo init machen für folders, bookmarks, parser, etc.

  def categorized?
    category_id.present?
  end

  def decayed?
    containing_elements_decayed?
  end

  def containing_elements_decayed? (threshold = 1.month)
    # lastedited updaten..
    max = _update_folders_last_edited_attribute
    if max.present?
      max + threshold < Time.now
    else
      false # is a folder without elements decayed?
    end
  end

  def _update_folders_last_edited_attribute (max = nil)
    # puts "calling this method"
    #todo refactor...
    max = bookmarks.map{|x| x.updated_at}.max
    if max.present?
      if lastedited != max
        self.lastedited= max
        self.save
      end
    end
    max
  end

  def empty?
    bookmarks.nil?
  end

  def derive_last_review_date
    #note0 schon zuvor welche gemacht. beginne hier zu zählen
    #todo english:
    # design notes ....
    # comes from the gtd methodology somehow.. !!
    # bisher nur elements_decayed. wird nur geupdated wenn bookmark
    # verändert oder wenn neues dazukommt.
    # wenn dann erst machen wenn schon todos assoziiert sind. oder aber
    # wenn folder komplett reviewed ist: d.h.:
    # save view_dates of bookmarks and complete acqurings.
    # acquirings < folder ....
  end














  # refactoring: problem point methods that act on groups of tabs

  def sort_by_edit_date_recursive
    # go down to all items and find out last edit date
    # give folders with items a weight with edit dates of
    # items in folder

    #push a folder if there is a new element contained.
  end

  def category_tree_assign root
    # e.g. "Kleidung" / clothing bookmarks folder
    # and subfolders to the category clothing
    # data structure in general: have a plain structure of
    # categories, maybe subcategories, and folders in there
    # see concepts of dashable 'research buckets' in sketches
    # for bookmarking system and for semantic web project '404'
  end

  def threshold_date_weight_function

  end

  def group_by_date
    # like in onetab. give threshold e.g. one day to group an aquiring(!)
    # refactored: moved this method out of bookmarks...
    # make a grouping helper method for the view.
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index_full
    #todo there was a problem with renaming this
  end

  def index
    # @folders = Folder.order('')
    @folders = Folder.order('parent_id, position')
    # @folders = Folder.all
    # order by size of folder ...
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @bookmarks = Bookmark.where('folder_id == ?', @folder.eid)
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:parent_id, :title, :position, :dateadded)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_folders.html.haml
%header
  .container_background
    .container_marks
      - @folders.each do |f|
        - if f.is_rootparent?
          =link_to f do
            .bm_vert
              %p= f.title
  .container_left

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true) do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :exportid %>
    <%= form.number_field :exportid, id: :folder_exportid %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.text_field :parent_id, id: :folder_parent_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :folder_title %>
  </div>

  <div class="field">
    <%= form.label :index %>
    <%= form.number_field :index, id: :folder_index %>
  </div>

  <div class="field">
    <%= form.label :dateadded %>
    <%= form.datetime_select :dateadded, id: :folder_dateadded %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>


<form>
  <fieldset>
    <input id="target" type="text" value="Hello there">
  </fieldset>
</form>
<div id="other">
  Trigger the handler
</div>

<script>
    $("#target").keypress(function () {
        console.log("Handler for .keypress() called.");
    });
</script>

app/views/folders/index.html.haml
-#-#- @folders.each do |f|
-#-#  - if f.is_rootparent?
-#-#    = link_to f.title, f, class:"btn btn-warning"
-#-#  - elsif f.decayed?
-#-#    = link_to f.title, f, class:"btn btn-primary"
-#-#  - else
-#-#    = link_to f.title, f, class:"btn btn-secondary"- @folders.each do |f|
-#
-#
%header
  .container_background
    .container_marks
      - @folders.each do |f|
        - if f.is_rootparent?
          =link_to f do
            .bm_vert
              %p= f.title
  .container_left
    -#.bm_base_down
      hello hello
    .container_folders_tags
      .bm_horiz.selected
        %p hey bookmark
      .tag_down
      .bm_horiz
      .bm_horiz
      .bm_horiz
      .bm_horiz
.mainbody
  -#.window_up

app/views/folders/index_full.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Exportid</th>
      <th>Parent</th>
      <th>Title</th>
      <th>Index</th>
      <th>Dateadded</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.exportid %></td>
<!--        <td><%#= folder.parent %></td>-->
        <td><%= folder.parent_id %></td>
        <td><%= folder.title %></td>
        <td><%= folder.position %></td>
        <td><%= folder.dateadded %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.haml
%h3= @folder.title

- @bookmarks.each do |b|
  %ul.folders
    %li= link_to b.title, b